theme: jekyll-theme-cayman
title: [The ODsL Project]
description: [The ODsL project aims to engage the data science and open source communities in a discussion about open code & data licenses suitable for a data-driven future.]